sudo: false
language: python
dist: bionic   # required for Python >= 3.7
cache: pip

# Environment changes have to be manually synced with 'tox.ini'.
# See: https://github.com/travis-ci/travis-ci/issues/3024

matrix:
  include:
  - python: '3.5'
    dist: xenial  # Bionic has no Python 3.5
    env: TOXENV=py35
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.7'
    env: TOXENV=py37
  - python: '3.7'
    env: TOXENV=qa
  - python: '3.7'
    env: TOXENV=docs

    # Disabled, see https://github.com/sybrenstuvel/python-rsa/issues/131
    #- python: pypy3.5
    #  dist: xenial  # Bionic has no Python 3.5
    #  env: TOXENV=pypy3

install:
  - pip install poetry
  - poetry install -v

script:
  - poetry run tox

after_success:
  # Coveralls submission only for py36 environment, because of being the only
  # one that executes doctest-modules testing, according to tox.ini.
  - if [ ${TOXENV} = "py37" ]; then coveralls; fi
